config/routes.rb
Rails.application.routes.draw do
  root to: "requests#index"

  resources :requests do
    resources :request_drugs
  end

  resources :drugs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :drugs

end

app/models/customer_drug.rb
class CustomerDrug < ApplicationRecord
  belongs_to :request
  has_many :dosages, dependent: :destroy

  accepts_nested_attributes_for :dosages, allow_destroy: true, reject_if: :all_blank
end

app/models/dosage.rb
class Dosage < ApplicationRecord
  belongs_to :customer_drug

  #belongs_to :requests
end

app/models/drug.rb
class Drug < ApplicationRecord
  has_many :request_drugs
  has_many :requests, through: :request_drugs
  belongs_to :country, optional: true
end

app/models/request.rb
class Request < ApplicationRecord

  include Models::Request::XmlParse

  has_many :request_drugs, dependent: :destroy
  has_many :drugs, through: :request_drugs
  has_many :customer_drugs, dependent: :destroy

  accepts_nested_attributes_for :request_drugs, allow_destroy: true, reject_if: :all_blank
  accepts_nested_attributes_for :customer_drugs, allow_destroy: true, reject_if: :all_blank


  validates :auction_number, presence: true


end

app/models/request_drug.rb
class RequestDrug < ApplicationRecord
  belongs_to :request
  belongs_to :drug
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/drugs_controller.rb
class DrugsController < ApplicationController
  before_action :set_drug, only: [:show, :edit, :update, :destroy]
  before_action :set_country, only: [:show, :edit]

  def index
    @drugs = Drug.all
  end

  def show
  end

  def new
    @drug = Drug.new
  end

  def edit
  end

  def create
    @drug = Drug.new(drug_params)

    if @drug.save
      redirect_to @drug, notice: 'Drug was successfully created.'
    else
      render :new
    end
  end

  def update
    if @drug.update(drug_params)
      redirect_to @drug, notice: 'Drug was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @drug.destroy

    redirect_to drugs_url, notice: 'Drug was successfully destroyed.'
  end

  private
    def set_drug
      @drug = Drug.find(params[:id])
    end

    def set_country
      @countries = Country.all
    end

    def drug_params
      params.require(:drug).permit(:id, :mnn, :name, :country_id, :dosage_form, :packing, :producer, :unit)
    end
end

app/controllers/request_drugs_controller.rb
class RequestDrugsController < ApplicationController
  before_action :set_request_drug, only: [:show, :edit, :update, :destroy]

  def index
    @request_drugs = RequestDrug.all
  end

  def show
  end

  def new
    @request_drug = RequestDrug.new
  end

  def edit
  end

  def create
    @request = Request.find(params[:request_id])
    @new_request_drug = @request.request_drugs.build(request_drug_params)

    if @new_request_drug.save
      redirect_to @request, notice: 'Request drug was successfully created.'
    else
      render :new
    end
  end

  def update
    if @request_drug.update(request_drug_params)
      redirect_to @request_drug, notice: 'Request drug was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @request_drug.destroy

    redirect_to @request_drug.request, notice: 'Request drug was successfully destroyed.'
  end

  private

    def set_request_drug
      @request_drug = RequestDrug.find(params[:id])
    end

    def request_drug_params
      params.require(:request_drug).permit(:id, :drug_id, :request_id)
    end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: [:show, :edit, :update, :destroy]

  def index
    @requests = Request.all
  end

  def show
    @request_drugs = @request.request_drugs.all
    @new_request_drug = @request.request_drugs.build
    @drugs = Drug.all.map{ |drug| [ "#{drug.name} | #{drug.mnn}", drug.id ] }
  end

  def new
    @request = Request.new
    #@new_request_drug = @request.request_drugs.build
    #@drugs = Drug.all.map{ |drug| [ "#{drug.name} | #{drug.mnn}", drug.id ] }
  end

  def edit
  end

  def create
    @request = Request.new(request_params)
    if params[:get_data_button]
      get_xml_data
      render :new
    else
      if @request.save
        redirect_to edit_request_path(@request.id), notice: 'Request was successfully created.'
      else
        render :new
      end
    end
  end

  def update
    if params[:get_data_button]
      get_xml_data
      render :edit
    else

      if @request.update(request_params)
        redirect_to edit_request_path(@request.id), notice: 'Request was successfully updated.'
      else
        render :edit
      end
    end
  end

  def destroy
    @request.destroy

    redirect_to requests_url, notice: 'Request was successfully destroyed.'
  end

  private

    def set_request
      @request = Request.find_by(id: params[:id])
    end

    def request_params
      params.require(:request).permit(:id, :auction_number, :customer, :etp, :number,
       :purchase_info, :max_price, :delivery_time, :delivery_place, :exp_date,
       request_drugs_attributes: [:id, :drug_id, :request_id, :quantity, :_destroy, :unit],
       customer_drugs_attributes: [
         :id, :mnn, :quantity, :price, :cost,
         dosages_attributes: [:id, :form, :value, :unit, :customer_drug_id]
       ]
       )
    end

    def get_xml_data
      #ZakupkiXmlService.call(@request) if @request.valid?
      @request.xml_parse if @request.valid?
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drugs_helper.rb
module DrugsHelper
end

app/helpers/request_drugs_helper.rb
module RequestDrugsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/drugs/_drug.html.erb
<div>
  <%= link_to "#{drug.name}  #{drug.mnn}", drug %>

  <%#= link_to 'Show', drug %>
  <%#= link_to 'Edit', edit_drug_path(drug) %>
  <%#= link_to 'Destroy', drug, method: :delete, data: { confirm: 'Are you sure?' } %>
</div>

app/views/drugs/_form.html.erb
<%= simple_form_for @drug do |f| %>
  <%= f.input :mnn %>
  <%= f.input :name %>
  <%= f.input :dosage_form,  as: :text%>
  <%= f.input :unit %>
  <%= f.input :packing %>
  <%= f.input :producer %>
  <%= f.association :country, collection: @countries %>

  <%= f.button :submit, 'Сохранить', class: 'btn btn-primary' %> или <%= link_to 'вернуться', drugs_path%>
<% end %>

app/views/drugs/edit.html.erb
<h1>Editing Drug</h1>

<%= render 'form', drug: @drug %>

<%= link_to 'Show', @drug %> |
<%= link_to 'Back', drugs_path %>

app/views/drugs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Препараты</h1>

<%= render partial: 'drug', collection: @drugs %>

<%= link_to 'New Drug', new_drug_path %>

app/views/drugs/new.html.erb
<h1>New Drug</h1>

<%= render 'form', drug: @drug %>

<%= link_to 'Back', drugs_path %>

app/views/drugs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= render partial: 'form', object: @drug %>
</p>

<%= link_to 'Edit', edit_drug_path(@drug) %> |
<%= link_to 'Back', drugs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Requests</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>

  <body>
  <div class="container">
    <div class="row">
      <div class="col-lg-10">
        <%= yield %>
      </div>
    </div>
  </div>
  </body>
</html>

app/views/request_drugs/_form.html.erb
<%= form_for [@request, @new_request_drug] do |f| %>
  <%= f.select(:drug_id, drugs) %>

  <%= f.submit 'Добавить', class: 'btn btn-primary' %>
<% end %>

app/views/request_drugs/_request_drug.html.erb
<div>
  <%= link_to "#{request_drug.drug.name}  #{request_drug.drug.mnn}", request_drug.drug %>
  <%= link_to "Remove", request_request_drug_path(request_drug.request, request_drug),
              method: :delete, data: { confirm: 'Are you sure?' } %>

</div>

app/views/request_drugs/edit.html.erb
<h1>Editing Request Drug</h1>

<%= render 'form', request_drug: @request_drug %>

<%= link_to 'Show', @request_drug %> |
<%= link_to 'Back', request_drugs_path %>

app/views/request_drugs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Request Drugs</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @request_drugs.each do |request_drug| %>
      <tr>
        <td><%= link_to 'Show', request_drug %></td>
        <td><%= link_to 'Edit', edit_request_drug_path(request_drug) %></td>
        <td><%= link_to 'Destroy', request_drug, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Request Drug', new_request_drug_path %>

app/views/request_drugs/new.html.erb
<h1>New Request Drug</h1>

app/views/requests/_dosage.html.erb
<div>
  <% if dosage_counter == 0 %>
    Основной вариант поставки:
  <% else %>
    Альтернативные варианты поставки:
  <% end %>

  <%= "#{dosage.form}, #{dosage.value}, #{dosage.unit}" %>
</div>

app/views/requests/_form.html.erb
<%= simple_form_for @request do |f| %>
  <%= f.input :auction_number %>

  <%= f.input :etp %>

  <%= f.input :purchase_info, as: :text %>

  <%= f.input :max_price %>

  <%= f.input :customer, as: :text %>

  <%= f.input :delivery_place, as: :text %>

  <%= f.input :delivery_time, as: :text %>

  <%= f.input :exp_date %>

  <%= f.button :submit, 'Сохранить', class: 'btn btn-primary' %> или <%= link_to 'вернуться', requests_path%>

  <%= f.button :submit, 'Получить данные', name: 'get_data_button', class: 'btn btn-info' %>

  <div id="tasks" class="mt-3">
    <div class="row">
      <div class="col-md-12">
        <%= f.simple_fields_for :request_drugs do |request_drug| %>
          <%= render 'request_drug_fields', f: request_drug %>
        <% end %>

        <div class="links">
          <%= link_to_add_association 'Добавить препарат', f, :request_drugs, class: 'btn btn-primary form-control' %>
        </div>
      </div>
    </div>
  </div>

  <div class="customer_drugs mt-5">
    <p class="font-weight-bold">Препараты из документации</p>
    <table class="table table-bordered customer_drugs_table">
      <% if @request.customer_drugs.present? %>
        <thead class="table-secondary">
        <tr class="text-center ">
          <th class="align-middle">МНН</th>
          <th class="align-middle">Сведения о лекарственных формах, дозировках и единицах измерения</th>
          <th class="align-middle">Количество</th>
          <th class="align-middle">Цена за единицу</th>
          <th class="align-middle">Стоимость</th>
        </tr>
        </thead>
      <% end %>

      <% @request.customer_drugs.each do |drug| %>
        <tr>
          <td><%= drug.mnn %></td>
          <td><%= render partial: 'dosage', collection: drug.dosages %></td>
          <td class="text-center"><%= drug.quantity %></td>
          <td class="text-center"><%= drug.price %></td>
          <td class="text-center"><%= drug.cost %></td>
        </tr>
      <% end %>

    </table>
  </div>

  <%= f.simple_fields_for :customer_drugs do |f_drug| %>
    <%= f_drug.hidden_field :mnn %>
    <%= f_drug.hidden_field :quantity %>
    <%= f_drug.hidden_field :price %>
    <%= f_drug.hidden_field :cost %>

    <%= f_drug.simple_fields_for :dosages do |f_dosage| %>
      <%= f_dosage.hidden_field :form %>
      <%= f_dosage.hidden_field :value %>
      <%= f_dosage.hidden_field :unit %>
    <% end %>
  <% end %>
<% end %>

app/views/requests/_request.html.erb
<div>
  <%= link_to "#{request.auction_number} #{request.customer}", request %>
  <%= link_to 'Edit', edit_request_path(request) %>
  <%= link_to 'Destroy', request, method: :delete, data: { confirm: 'Are you sure?' } %>
</div>

app/views/requests/_request_drug_fields.html.erb
<div class="nested-fields">
  <div class="row">
    <div class="col-md-6">
      <%= f.association :drug, collection: Drug.all, label: false %>
    </div>

    <div class="col-md-3">
      <%= f.input :unit, label: false %>
    </div>

    <div class="col-md-2">
      <%= f.input :quantity, label: false %>
    </div>

    <div class="col-md-1">
      <%= link_to_remove_association 'Удалить', f, class: 'btn btn-danger' %>
    </div>
  </div>
</div>

app/views/requests/edit.html.erb
<h1>Редактирование заявки</h1>

<%= render 'form', request: @request %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

app/views/requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Заявки</h1>

<%= render partial: 'request', collection: @requests %>

<%= link_to 'Новая заявка', new_request_path, class: 'btn btn-primary' %>

app/views/requests/new.html.erb
<h1>Новая заявка</h1>

<%= render 'form', request: @request %>

app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>

<div class="text-justify">
  <p>Изучив документацию об электронном аукционе (извещение № <%= @request.auction_number %>)
    на право заключить государственный контракт на <%= @request.purchase_info %>,
    сообщаем вам о согласии поставить товар в соответствии с требованиями и на условиях,
    предусмотренных документацией об электронном аукционе.
  </p>

  <p><span class="font-weight-bold">Сведения о товаре:</span> Требования к качеству, техническим характеристикам товара, требования
    к их безопасности, требования к функциональным характеристикам (потребительским свойствам) товара,
    требования к размерам, упаковке, отгрузке товара и иные показатели, связанные с определением соответствия
    поставляемого товара, потребностям заказчика
  </p>
</div>

<table class="table table-bordered request-table">
  <thead class="table-secondary">
    <tr class="text-center">
      <th class="align-middle">№ п/п</th>
      <th class="align-middle">Международное непатентованное название</th>
      <th class="align-middle">Наименование товара, указание на товарный знак (при его наличии) предлагаемого участником размещения заказа</th>
      <th class="align-middle">Форма выпуска (согласно записи в государственном реестре лекарственных средств)</th>
      <th class="align-middle">Страна происхождения</th>
      <th class="align-middle">Ед. изм.</th>
      <th class="align-middle">Кол-во</th>
      <th class="align-middle">Ед. изм.</th>
      <th class="align-middle">Кол-во</th>


    </tr>
  <thead>
  <% @request_drugs.each_with_index do |request_drug, number| %>
    <tr>
      <td class="text-center"><%= number + 1 %></td>
      <td><%= request_drug.drug.mnn %></td>
      <td><%= request_drug.drug.name %></td>
      <td><%= request_drug.drug.dosage_form %></td>
      <td><%#= "#{request_drug.drug.country.name}, #{request_drug.drug.country.code}" %></td>
      <td><%= request_drug.drug.unit %></td>
      <td><%= request_drug.drug.packing %></td>
      <td class="text-center"><%= request_drug.unit %></td>
      <td class="text-center"><%= request_drug.quantity %></td>
    </tr>
  <% end %>
</table>

<div class="text-justify">
  <ul class="list-group">
    <li class="list-group-item">Поставляемый  товар  соответствует  ГОСТам,  международным стандартам. Товарная позиция соответствует по составу,
      фармакологическому действию, фармокинетике, показаниям,  режиму дозирования, побочным действиям, противопоказаниям,
      лекарственному взаимодействию, форме выпуска, дозировке, расфасовке, упаковке, условиям и срокам хранения.
    </li>

    <li class="list-group-item"><span class="font-weight-bold">Остаточный срок годности:</span> <%= @request.exp_date %></li>
    <li class="list-group-item"><span class="font-weight-bold">Срок поставки товара:</span> <%= @request.delivery_time %></li>
    <li class="list-group-item"><span class="font-weight-bold">Место поставки товара:</span> <%= @request.delivery_place %></li>
  </ul>
</div>
<%#= render partial: 'request_drugs/request_drug', collection: @request_drugs %>

<%#= render partial: 'request_drugs/form', locals:{drugs: @drugs} %>


<!--<%#= link_to 'Edit', edit_request_path(@request) %> |-->
<%#= link_to 'Back', requests_path %>